### ISSUE TITLE
cannot find -lsqlite3

### ISSUE THREAD

**Issue by hasanOryx** [stainless-steel/sqlite3-src#3]
I'm using `macOS`, and trying to compile for `Android` using the command
```bash
cargo build --target x86_64-linux-android --release
```

I got the error while compiling the [rusqlite](https://github.com/jgallagher/rusqlite) which is depending on your library

> = note: /Users/../NDK/x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lsqlite3
> clang70: error: linker command failed with exit code 1 (use -v to see invocation)                        

I already have sqlite3 installed:
```bash
Hasans-Air:~ h_ajsf$ brew install sqlite
Warning: sqlite 3.26.0 is already installed and up-to-date
To reinstall 3.26.0, run `brew reinstall sqlite`
```

And it compiled smoothly for mac lib, using
```bash
cargo build --release
```

**Comment by IvanUkhov** [comment]
As one can see in `build.rs`, cross-compilation is not supported at the moment. As a workaround, you could activate the `bundled` feature and do the linking yourself.

**Comment by hasanOryx** [comment]
Any idea how to make it?

**Comment by IvanUkhov** [comment]
Sorry, I haven’t tried. I suppose one has to make sure that the right compiler is chosen. Probably the [`cc`](https://github.com/alexcrichton/cc-rs) crate, which is already used for compiling, does something like that under the hood. Maybe all one needs is to set some environment variables. Take a look at what they write in the documentation.
