### ISSUE TITLE
Issues with openssl when cross-compiling 

### ISSUE THREAD

**Issue by packadal** [stainless-steel/sqlite3-src#5]
Hi, 
when cross-compiling on a clean env, I get the following issue:

>   cargo:warning=sqlcipher/sqlite3.c:105787:10: fatal error: openssl/crypto.h: No such file or directory
  cargo:warning=105787 | #include <openssl/crypto.h>
  cargo:warning=       |          ^~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1
  --- stderr

should a dependency to openssl-sys be added ?

**Comment by IvanUkhov** [comment]
It seems to be coming from a different dependency. I see sqlcipher in the path, and I do not see such a header in the source:

https://github.com/copies/sqlite/tree/main

**Comment by packadal** [comment]
oops, my bad, sorry
